In [15]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [16]:
data = pd.read_csv("Train.csv")

In [17]:
data.head(5)

feature_1  feature_2  feature_3  feature_4  feature_5     target
0   0.293416  -0.945599  -0.421105   0.406816   0.525662 -82.154667
1  -0.836084  -0.189228  -0.776403  -1.053831   0.597997 -48.897960
2   0.236425   0.132836  -0.147723   0.699854  -0.187364  77.270371
3   0.175312   0.143194  -0.581111  -0.122107  -1.292168  -2.988581
4  -1.693011   0.542712  -2.798729  -0.686723   1.244077 -37.596722

In [18]:
data = data.values

In [28]:
print (data[:,0])

[ 0.29341624 -0.83608408  0.23642511 ...  1.04417694 -1.2691729
 -1.88400025]


In [59]:
def hypothesis(X,theta):
    return theta[0]+theta[1]*X[0]+theta[2]*X[1]+theta[3]*X[2]+theta[4]*X[3]+theta[5]*X[4]


In [30]:
X=data[:,:5]

In [31]:
X.shape

(1600, 5)

In [33]:
type(X)

numpy.ndarray

In [34]:
ones = np.ones((X.shape[0],1))

In [35]:
X=np.hstack((ones,X))
X.shape

(1600, 6)

In [36]:
print(X[:5,:])

[[ 1.          0.29341624 -0.94559871 -0.42110515  0.40681602  0.52566183]
 [ 1.         -0.83608408 -0.18922804 -0.77640262 -1.05383124  0.59799685]
 [ 1.          0.23642511  0.13283602 -0.14772298  0.69985396 -0.18736416]
 [ 1.          0.17531181  0.14319424 -0.58111096 -0.12210693 -1.29216807]
 [ 1.         -1.69301097  0.54271187 -2.79872942 -0.68672304  1.24407683]]


In [37]:
data[:,5]

array([ -82.15466656,  -48.89796018,   77.2703707 , ..., -107.51050797,
        -47.34155781, -115.93900296])

In [38]:
Y=data[:,5]

In [39]:
Y.shape

(1600,)

In [42]:
Y= Y.reshape((-1,1))

In [43]:
Y.shape

(1600, 1)

In [44]:
# Applying Formula For Closed Form

In [45]:
theta = np.dot(np.linalg.pinv(np.dot(X.T,X)),np.dot(X.T,Y))

In [46]:
theta.shape

(6, 1)

In [47]:
theta = theta.reshape((-1,))

In [48]:
print(theta.shape)
print(theta)

(6,)
[ 4.99096674 29.68187118 92.66247759  8.28062089 44.76773522  2.51916121]


# Testing The Algorithm

In [61]:
test = pd.read_csv("Test.csv")

In [62]:
test.head(5)

feature_1  feature_2  feature_3  feature_4  feature_5
0   1.015254   2.076209  -0.266435  -2.418088  -0.980503
1  -0.375021   0.953185   0.626719   0.704406  -0.355489
2  -1.024452   0.962991  -0.407942  -1.861274   0.455201
3  -2.489841   0.544802   0.601219  -0.607021  -1.314286
4  -0.384675  -0.833624   1.358552  -0.547932   0.411925

In [63]:
pred = []
test.shape
test = test.values
test.shape

(400, 5)

In [66]:
test[0,:]

array([ 1.01525387,  2.07620944, -0.26643482, -2.4180882 , -0.98050279])

In [67]:
for ix in range(test.shape[0]):
    pred.append(hypothesis(test[ix,:],theta))

In [77]:
pred = np.array(pred)

In [79]:
pred.shape

(400,)

In [81]:
pred = pred.reshape(-1,1)

In [82]:
pred.shape

(400, 1)

In [103]:
#fin=[]

In [104]:
#for ix in range(pred.shape[0]):
 #   fin.append([ix,pred[ix]])

In [105]:
#fin = np.array(fin)

In [106]:
#fin.shape

In [116]:
sub = pd.DataFrame(pred)

In [117]:
sub.to_csv("Submission.csv")

In [125]:
tsub = pd.read_csv("Submission.csv")

In [126]:
tsub.head(5)

Unnamed: 0           0
0           0  114.583689
1           1  118.012815
2           2  -21.739852
3           3  -43.936899
4           4  -95.914898

In [127]:
tsub.columns

Index(['Unnamed: 0', '0'], dtype='object')

In [128]:
tsub.columns = ['Id','target']

In [129]:
tsub.columns

Index(['Id', 'target'], dtype='object')

In [130]:
tsub.head(5)

Id      target
0   0  114.583689
1   1  118.012815
2   2  -21.739852
3   3  -43.936899
4   4  -95.914898

In [137]:
tsub.to_csv("Submission1.csv",index = False)

In [138]:
msub = pd.read_csv("Submission1.csv")

In [139]:
msub.head(5)

Id      target
0   0  114.583689
1   1  118.012815
2   2  -21.739852
3   3  -43.936899
4   4  -95.914898

In [135]:
msub.drop('Unnamed: 0', axis=1, inplace=True)

In [136]:
msub.head(5)

Id      target
0   0  114.583689
1   1  118.012815
2   2  -21.739852
3   3  -43.936899
4   4  -95.914898